### ISSUE TITLE
bmaptool copy of compressed images fail with url that don't end with a recognized compressed file extension

### ISSUE THREAD

**Issue by alambert-pbsc** [intel/bmap-tools#100]
**Summary**
bmaptool copy function returns a Checksum Error when the image is a compressed image but its URL doesn't end with a recognized compressed file extension

**Steps to reproduce**
bmaptool copy --bmap URL_TO_BMAP_FILE URL_TO_COMPRESSED_IMAGE_FILE DESTINATION
where URL_TO_COMPRESSED_IMAGE_FILE must not end with a recognized compressed file extension

**Actual results**
Copy fails and return a Checksum Error

**Expected results**
Copy succeed

**Root cause**
It seems to be caused by the TransRead module which detect if a file is compressed by parsing the file extension from the string passed to the tool (which would not work in some cases with URL which ends with query strings)

**Possible fixes**
Easiest would be to ignore the query string from the URL. 
Better fix could be to get the actual filename from the Content-Disposition HTTP header.

**Comment by vivien** [comment]
I have this exact problem where CloudFront is used to generate [signed URLs](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-creating-signed-url-canned-policy.html) for built artifacts. The compressed image and bmap file end up with very a long suffix containing URI parameters `Expires=`, `Signature=` and `Key-Pair-Id`. Here is an example of such signed URL:

    https://some.server.net/sdcard.wic.lz4?Expires=1357034400&Signature=nitfHRCrtziwO2HwPfWw~yYDhUF5EwRunQA-j19DzZrvDh6hQ73lDx~-ar3UocvvRQVw6EkC~GdpGQyyOSKQim-TxAnW7d8F5Kkai9HVx0FIu-5jcQb0UEmatEXAMPLE3ReXySpLSMj0yCd3ZAB4UcBCAqEijkytL6f3fVYNGQI6&Key-Pair-Id=K2JCJMDEHXQW5F

Such files can be hosted and accessed publicly, i.e. wget works just fine (which is the current workaround to the problem).

**Comment by dedekind** [comment]
Hi, same comment - I do not have time for this project. Everyone is welcome to contribute, demonstrate that he/she is capable of taking care of the project and become the maintainer. Thanks!

**Comment by dedekind** [comment]
Hello, the project was moved and now owned by a new team. Please, work with them. Check the README.md file. Thanks!
