### ISSUE TITLE
Support for concatenated bmap file format

### ISSUE THREAD

**Issue by vivien** [intel/bmap-tools#101]
In some setup, it is not always possible to deduce the URL of the bmap file from the URL of the image file. It would be beneficial to introduce a new image format prepended with the bmap file, bmaptool could then work with the image from a given offset deduced via the prepended bmap info. Additionally, a more complex format could embed the signature files as well.

**Comment by dedekind** [comment]
May be. Or allow for them to be contantenated, Basically figure out a way to deliver them as a single file, which can be effeciently split during downloading. Like we download, watch the stream, see an "end of bmap, start of the image" marker, and start saving to a separate file.

In any case, I do not have time for this project. This entire project was very useful for me in the past, but I am not involved. The whole project needs a maintainer or a group of people who care and have time for it. Also, I think we need to re-structure and even re-write some parts, I think we need to drop python2 too. Tests are currently broken too. But I have no time and no motivation for this. Feel free to contribute. Anyone who contributes and demonstrates that he/she is capable to take care of this project, can be the new maintainer.

**Comment by dedekind** [comment]
Hello, the project was moved and now owned by a new team. Please, work with them. Check the README.md file. Thanks!
