### ISSUE TITLE
tests fail after 2024-06-12

### ISSUE THREAD

**Issue by bmwiedemann** [intel/bmap-tools#116]
While working on [reproducible builds](https://reproducible-builds.org/) for [openSUSE](https://en.opensuse.org/openSUSE:Reproducible_Builds), I found that
our `bmap-tools-3.6` package fails to build after 2024-06-12.

To reproduce, you could set the system clock or use the following on Debian or openSUSE:
```
osc co openSUSE:Factory/bmap-tools && cd $_
osc build --clean --vm-type=kvm --noservice --build-opt=--vm-custom-opt="-rtc base=2024-06-13T00:00:00" standard
```

actual results:
```
tests/test_CLI.py::TestCLI::test_valid_signature FAILED
...

----------------------------- Captured stderr call -----------------------------
bmaptool: [91mERROR[0m: An error occurred, here is the traceback:
Traceback (most recent call last):
   File "/home/abuild/rpmbuild/BUILDROOT/bmap-tools-3.6-0.x86_64/usr/lib/python3.8/site-packages/bmaptools/CLI.py", line 205, in verify_detached_bmap_signature
    sigs = context.verify(signed_data, signature, None)[1].signatures
  File "/usr/lib64/python3.8/site-packages/gpg/core.py", line 558, in verify
    raise errors.BadSignatures(results[1], results=results)

bmaptool: [91mERROR[0m: discovered a BAD GPG signature: tests/test-data/signatures/test.image.bmap.v2.0.valid-sig
```

This is likely due to some expiring gpg key.

**Comment by Abooksks** [comment]
tests/test_CLI.py::TestCLI::test_valid_signature FAILED
...

----------------------------- Captured stderr call -----------------------------
bmaptool: �[91mERROR�[0m: An error occurred, here is the traceback:
Traceback (most recent call last):
   File "/home/abuild/rpmbuild/BUILDROOT/bmap-tools-3.6-0.x86_64/usr/lib/python3.8/site-packages/bmaptools/CLI.py", line 205, in verify_detached_bmap_signature
    sigs = context.verify(signed_data, signature, None)[1].signatures
  File "/usr/lib64/python3.8/site-packages/gpg/core.py", line 558, in verify
    raise errors.BadSignatures(results[1], results=results)

bmaptool: �[91mERROR�[0m: discovered a BAD GPG signature: tests/test-data/signatures/test.image.bmap.v2.0.valid-sig

**Comment by bmwiedemann** [comment]
2024-06-12 is less than 5 months from now. Any plans to avoid failing tests?

**Comment by dedekind** [comment]
@bmwiedemann hi, this project needs a maintaner, I do not have time for it any longer. I sent this e-mail to Yocto community:

https://lists.yoctoproject.org/g/yocto/message/62256

Feel free to volunteer to do this work for Yocto community.

**Comment by dedekind** [comment]
Hello, the project was moved and now owned by a new team. Please, work with them. Check the README.md file. Thanks!

**Comment by bnavigator** [comment]
```shell
# extend signing key expiration for reproducible builds
export GNUPGHOME=$PWD/tests/test-data/gnupg
echo 'expire
50y
key 1
expire
50y
save' | gpg --command-fd=0 --batch --edit-key 927FF9746434704C5774BE648D49DFB1163BDFB4
```
