### ISSUE TITLE
Support copying to a device block through ssh

### ISSUE THREAD

**Issue by Paiusco** [intel/bmap-tools#123]
A bit similar use-case as https://github.com/intel/bmap-tools/issues/74 

Currently, the way this is done in my case is to `dd if=` stdin from host and piping it to ssh running a `dd of=` to the target. It's on vendor documentation even, so I was thinking if it's possible to have something like:
`bmaptool copy <wic_file> <ssh_uri>/dev/<device>`

**Comment by dedekind** [comment]
Hi sure, it is possible to implement. But I do not have time for this, unfortunately. So someone needs to contribute this.

**Comment by dedekind** [comment]
Hello, the project was moved and now owned by a new team. Please, work with them. Check the README.md file. Thanks!
