### ISSUE TITLE
Compatibility issues with FAT file systems?

### ISSUE THREAD

**Issue by jan-kiszka** [intel/bmap-tools#128]
I'm hunting reproducible issues with FAT file systems written to non-empty media. It looks to me like we are missing some zero'ing of sectors that are now becoming FAT directory tables in the new image. The issue can be worked around by zero'ing out the image first or by using `--nobmap`.

Isn't there a conceptual problem with FAT and bmap? I'm seeing first bits in the code that address potential issues with other file systems, but there is noting for FAT yet, right?

**Comment by smcv** [comment]
The most likely reason for filesystem-specific issues is that bmaptool needs to somehow distinguish between "must be zero" sectors and "don't care" sectors. To do that, bmaptool relies on two assumptions.

 The filesystem creation tool must write out "must be zero" sectors explicitly:

```
write(offset of region that must be blank, 4K of zeroes);
```

and must not skip blanking "must be zero" sectors if they happen to contain zeroes already, like this pseudocode:

```
if (read(offset of region that must be blank, 4K) != 4K of zeroes)
    write(offset of region that must be blank, 4K of zeroes);
```

Also, when the filesystem creation tool explicitly writes out zeroes, the filesystem on which the image was created must preserve those zeroes as data, and must not optimize them into a "hole" in a sparse file. Typical Linux filesystems like ext4 and btrfs match this assumption, but ZFS often does not: it will sometimes optimize away explicitly-written zeroes into a "hole".

If both of those assumptions are met, then bmaptool can treat blocks of zeroes as "must be zero", treat "holes" in a sparse file as "don't care", and get a working result.

However, if either of those assumptions is broken, then bmaptool has no way to distinguish between "must be zero" and "don't care". So it will not work correctly, unless you can edit the block map to explicitly say what the "must be zero" regions are.

**Comment by smcv** [comment]
The purpose of bmaptool is that it speeds up imaging by not wasting time and I/O bandwidth on writing out "don't care" sectors; so if the information it is given doesn't distinguish between "must be zero" and "don't care", it can't do its job.

If you have a faster way to zero out a device than explicitly writing out each sector - like discard/TRIM for example - then you could work around that missing information by zeroing the device, and then imaging with bmaptool. The result of that would be that all the sectors that bmaptool thinks are "don't care" are actually zeroed, so it doesn't matter whether bmaptool is wrong about the distinction between "must be zero" and "don't care".

**Comment by jan-kiszka** [comment]
The issue was caused by an overly sparse copy of the image file prior to running `bmaptool create`. The original file correctly contained non-sparse zeros in the filesystems, including FAT.
