### ISSUE TITLE
Fail if artifact is compressed with unsupported algorithm

### ISSUE THREAD

**Issue by fmoessbauer** [intel/bmap-tools#132]
Currently, the compression algorithm is determined based on the file extension on a best-effort basis. This is implemented in [1].
If no compression algorithm matched, it is assumed that the artifact is compressed. This is non ideal, as the flashing then just fails due to incorrect checksums, without giving the user any indication about the root-cause. It would be better to just fail in this case, indicating that no support for that algorithm / file extension is available.

We observed this issue at a larger scale when transitioning from `.xz` compressed images to `.zst` compressed images, which required bmaptools >= 3.6, while many users still had 3.5 only.

- [1] https://github.com/intel/bmap-tools/blob/7ca37b169e4a775b6f3166b763b4286d5433a541/bmaptools/TransRead.py#L248

**Comment by dedekind** [comment]
Hello, the project was moved and now owned by a new team. Please, work with them. Check the README.md file. Thanks!
