### ISSUE TITLE
[Errno 25] Inappropriate ioctl for device on platform ppc64/ppc64le

### ISSUE THREAD

**Issue by tcler** [intel/bmap-tools#29]
Actual results:
  [root@ ~~/bmap-tools]# ./bmaptool  create $nfsmp/test.image
  bmaptool: [91mERROR[0m: cannot generate bmap for file '/mnt/nfs/test.image': cannot get block size for '/mnt/nfs/test.image': [Errno 25] Inappropriate ioctl for device

reason:
  ioctl(file_obj, 2, struct.pack('I', 0)) can not works on ppc64/ppc64le

this patch works for me:
```
diff --git a/bmaptools/BmapHelpers.py b/bmaptools/BmapHelpers.py
index 585695f..02e280c 100644
--- a/bmaptools/BmapHelpers.py
+++ b/bmaptools/BmapHelpers.py
@@ -62,9 +62,10 @@ def get_block_size(file_obj):
 
     # Get the block size of the host file-system for the image file by calling
     # the FIGETBSZ ioctl (number 2).
-    binary_data = ioctl(file_obj, 2, struct.pack('I', 0))
-    bsize = struct.unpack('I', binary_data)[0]
-    if not bsize:
+    try:
+        binary_data = ioctl(file_obj, 2, struct.pack('I', 0))
+        bsize = struct.unpack('I', binary_data)[0]
+    except IOError as err:
         stat = os.fstat(file_obj.fileno())
         if hasattr(stat, 'st_blksize'):
             bsize = stat.st_blksize
```

**Comment by tcler** [comment]
FIGETBSZ is defined here:
```
include/uapi/linux/fs.h:#define FIGETBSZ   _IO(0x00,2)	/* get the block size used for bmap */
```
I guess It's value might be different on platform ppc64~

**Comment by kad** [comment]
Thanks for reporting this. It might be not that much dependent on architecture, but more on filesystem implementation. In your case it seems you're trying to generate map on file that is placed on NFS share. With your fix, does it generate bmap correctly ? By correctly I mean "be able to detect holes in the sparse file".

**Comment by tcler** [comment]
Yes. after the patch it works fine now;

the FIGETBSZ value is 536870914 on ppc64 platform, and 2 on other archs;

```
[root@ibm-p8-kvm-10-guest-02 ~]# arch
ppc64
[root@ibm-p8-kvm-10-guest-02 ~]# cat test.c
#include <stdio.h>
#include <linux/fs.h>

int main(int argc, char *argv[])
{
        printf("FIGETBSZ == %d %u %hd %hu \n", FIGETBSZ, FIGETBSZ, FIGETBSZ, FIGETBSZ);
        return 0;
}
[root@ibm-p8-kvm-10-guest-02 ~]# gcc test.c
[root@ibm-p8-kvm-10-guest-02 ~]# ./a.out
FIGETBSZ == 536870914 536870914 2 2

[yjh@dhcp-12-238 ~]$ ./a.out
FIGETBSZ == 2 2 2 2
[yjh@dhcp-12-238 ~]$ arch
x86_64
```

**Comment by tcler** [comment]
More info: s/2/536870914/  also works on ppc64 platform:
```
        binary_data = ioctl(file_obj, 536870914, struct.pack('I', 0))
```

**Comment by kad** [comment]
Can you show what does `python -c "import os; print(os.uname())"` will print on your system ?
Regarding "works fine": does the resulted bmap file contained information about holes in sparse files ? In my test environment over NFS it crashes. but that might be related to NFS server implementation.

**Comment by tcler** [comment]
oops, sorry I should not use nfs as example(default nfs version doesn't support seek_data/hole)

please forget nfs here, got same result on xfs/ext4 \@ ppc64 platfrom

Again, the point is:
  the FIGETBSZ value is 536870914 on ppc64 platform, and 2 on other platfoms;

```
[root@ibm-p8-kvm-10-guest-02 bmap-tools]# lsb_release -sir
RedHatEnterpriseServer 7.4
[root@ibm-p8-kvm-10-guest-02 bmap-tools]# uname -irmpo
3.10.0-693.el7.ppc64 ppc64 ppc64 ppc64 GNU/Linux
[root@ibm-p8-kvm-10-guest-02 bmap-tools]# du /test*.image -h
50M     /test2.image
50M     /test.image
[root@ibm-p8-kvm-10-guest-02 bmap-tools]# ls -l /test*.image
-rw-r--r--. 1 root root 2148532224 9月   7 18:56 /test2.image
-rw-r--r--. 1 root root 2147483648 9月   7 18:56 /test.image
[root@ibm-p8-kvm-10-guest-02 bmap-tools]# ./bmaptool  create  /test2.image
bmaptool: ERROR: cannot generate bmap for file '/test2.image': cannot get block size for '/test2.image': [Errno 25] Inappropriate ioctl for device
[root@ibm-p8-kvm-10-guest-02 bmap-tools]# ./bmaptool  create  /test.image
bmaptool: ERROR: cannot generate bmap for file '/test.image': cannot get block size for '/test.image': [Errno 25] Inappropriate ioctl for device
```

replace 2 with 536870914, then it works
```
[root@ibm-p8-kvm-10-guest-02 bmap-tools]# sed -i 's/ioctl(file_obj,.2/ioctl(file_obj,536870914/' bmaptools/BmapHelpers.py
[root@ibm-p8-kvm-10-guest-02 bmap-tools]# ./bmaptool  create  /test.image
<?xml version="1.0" ?>
<!-- This file contains the block map for an image file, which is basically
     a list of useful (mapped) block numbers in the image file. In other words,
     it lists only those blocks which contain data (boot sector, partition
     table, file-system metadata, files, directories, extents, etc). These
     blocks have to be copied to the target device. The other blocks do not
     contain any useful data and do not have to be copied to the target
     device.

     The block map an optimization which allows to copy or flash the image to
     the image quicker than copying of flashing the entire image. This is
     because with bmap less data is copied: <MappedBlocksCount> blocks instead
     of <BlocksCount> blocks.

     Besides the machine-readable data, this file contains useful commentaries
     which contain human-readable information like image size, percentage of
     mapped data, etc.

     The 'version' attribute is the block map file format version in the
     'major.minor' format. The version major number is increased whenever an
     incompatible block map format change is made. The minor number changes
     in case of minor backward-compatible changes. -->

<bmap version="2.0">
    <!-- Image size in bytes: 2.0 GiB -->
    <ImageSize> 2147483648 </ImageSize>

    <!-- Size of a block in bytes -->
    <BlockSize> 4096 </BlockSize>

    <!-- Count of blocks in the image file -->
    <BlocksCount> 524288 </BlocksCount>

    <!-- Count of mapped blocks: 50.0 MiB or 2.4%    -->
    <MappedBlocksCount> 12800  </MappedBlocksCount>

    <!-- Type of checksum used in this file -->
    <ChecksumType> sha256 </ChecksumType>

    <!-- The checksum of this bmap file. When it is calculated, the value of
         the checksum has be zero (all ASCII "0" symbols).  -->
    <BmapFileChecksum> 0056856c8007f7c43d1ed8c66222fdc265dc9712f97da86236fa50384f0576bc </BmapFileChecksum>

    <!-- The block map which consists of elements which may either be a
         range of blocks or a single block. The 'chksum' attribute
         (if present) is the checksum of this blocks range. -->
    <BlockMap>
        <Range chksum="8565a714dca840f8652c5bae9249ab05f5fb5a4f9f13fbe23304b10f68252da2"> 511488-524287 </Range>
    </BlockMap>
</bmap>
[root@ibm-p8-kvm-10-guest-02 bmap-tools]#
```

**Comment by dedekind** [comment]
The problem has nothing to do with FS specifics I believe, but rather related to platform specifics. The way IOCTL numbers are constructed is platform dependent. There is endiannes in play, to start with, but there are other things too (different lengths of various components of the final IOCTL number).

So just using number 2 for the FIGETBSZ ioctl and number 0xC020660B for the FIEMAP ioctl as we will only work for x86. PPC needs different numbers. ARM/MIPS will need yet different numbers.

I suggest checking out this project (it has very liberal license):
https://github.com/olavmrk/python-ioctl

**Comment by tcler** [comment]
Yes, your got it. hard code is bad; we need a ultimate solution to solve the problem that use *C MACRO* in python.

But I'm curious why not just use os.fsstat got get the  *bsize* here
```
  os.fstat(file_obj.fileno()).st_blksize # workaround
```

**Comment by dedekind** [comment]
This sounds like a good idea to me. I would advocate for the full removal of the helper even. Attaching a quick untested example of what I mean.

[untested-patch.txt](https://github.com/01org/bmap-tools/files/1287170/untested-patch.txt)

**Comment by kad** [comment]
I'm also more in favour of using only os.fstat() to get block size in all places, but keep helper, so error handling will be in one single place. That bit is easy to fix.

My additional questions were to clarify if we have other issues due to ppc64, because another ioctl FIEMAP. But that second part seems to be successfully falling back to seek method.

**Comment by dedekind** [comment]
Agree on keeping the helper and adding the 'hasattr(stdata, 'st_bklsize')' check there.

As to the falling back, we need to at least add a comment near the FIEMAP ioctl constant definition telling that we know the number we use is x86-only, and it won't work for other platforms.
