### ISSUE TITLE
Simple bmap parser

### ISSUE THREAD

**Issue by lurch** [intel/bmap-tools#38]
I've no idea if it's useful or not, but to get a handle on how bmap files work, I recently wrote a from-scratch parser which is kind of like a minimal implementation of `bmaptool copy`. (it only uses modules from the Python stdlib, nothing from bmap-tools)
https://gist.github.com/lurch/029674351674daa45511dba0d842fe4a

If it's useful, feel free to include it in your repo; if it's not useful feel free to close this issue :slightly_smiling_face:

**Comment by dedekind** [comment]
I personally do not use bmap-tools nowadays so I cannot say this snippet is useful. If you are a project user and you want this merged, create a pull request or otherwise give some explanation on

1. Why is this needed, which problem it solves, which benefits bring
2. How you integrate it - remove the existing code or will this parser co-exist, etc.

Thanks!

**Comment by lurch** [comment]
It doesn't "solve any problems", it's just a simple example of how little code it _can_ take to read a bmap file. (Which might be a useful starting point if a non-Python project wants to be able to parse bmaps? When I started writing this minimal-parser I didn't realise `bmaptool` was itself written in Python :wink: )

It shouldn't replace any of the existing code in the repo, so I'll close this issue.

**Comment by dedekind** [comment]
Well, may be you can add this to the project as an example or something like this.

**Comment by lurch** [comment]
I guess the Wiki would be an ideal place, but it doesn't seem to be working?

**Comment by dedekind** [comment]
I've created a dummy page, should work now

**Comment by lurch** [comment]
Seems like I can't edit it though... :-/

**Comment by dedekind** [comment]
How about creating an "examples" directory and adding this snippet there. Just add a nice header comment explaining your message - what is this about, etc.

**Comment by lurch** [comment]
See #40 - happy to make any changes requested.
