### ISSUE TITLE
MacOS X support

### ISSUE THREAD

**Issue by kad** [intel/bmap-tools#4]
Minimal MacOS X support:
- don't crash, generate nice error message for bmap generation code
- perform write operation as best as possible under MacOS X

**Comment by bartosh** [comment]
Hm, "bmaptool copy" worked for me on my Mac.

**Comment by parkasalfluke** [comment]
HI , Need bmap-tool support for Mac OSX

**Comment by tzahari** [comment]
Hi, I get the following error message within Mac OS 10.15.7:
`
thza@MacBook-Pro ~/bin [1]> sudo ./bmaptool copy --bmap file.wic.bmap file.wic /dev/disk3
bmaptool: ERROR: the image file 'file.wic' has size 1.0 GiB and it will not fit the block device '/dev/disk3' which has 0 bytes capacity
`
Mac OS X support would be great!

**Comment by kad** [comment]
@tzahari do you see same error if you use /dev/rdisk3 as argument?

**Comment by tzahari** [comment]
Hurray, it is working with the rdisk device. Thank you @kad

**Comment by dedekind** [comment]
Hello, the project was moved and now owned by a new team. Please, work with them. Check the README.md file. Thanks!
