### ISSUE TITLE
Please replace python-gpgme code with python-gpg

### ISSUE THREAD

**Issue by smcv** [intel/bmap-tools#43]
python-gpgme has been abandoned upstream, with python-gpg (part of GPGME, which is maintained by the GnuPG developers) as the recommended replacement.

The interface is broadly similar but has some differences. https://github.com/pazz/alot/pull/906/files is an example of a project being ported from python-gpgme to python-gpg.

**Comment by dedekind** [comment]
Thank you @mntns !
