### ISSUE TITLE
Support for machine parsable progress status

### ISSUE THREAD

**Issue by agherzan** [intel/bmap-tools#62]
I'm looking to figure out how to get the progress bar of a bmap copy process for further processing. Currently, only parsing the output is not helping because we are having an interactive progress status. I was thinking of implementing support for a named pipe. What do you think?

**Comment by dedekind** [comment]
Sure. Would be good to research how things like this are done in good tools, and mimic that approach.

**Comment by agherzan** [comment]
Well, that's the problem I guess: I am not aware of any too tool having this feature. Do you happen to know any examples?

**Comment by dedekind** [comment]
There is a pull request, it just needs to be amended, any volunteers to finish that work?

**Comment by dedekind** [comment]
@agherzan , can we assume this is fixed now when your psplash work was merged? Thanks!

**Comment by agherzan** [comment]
Sure. Thanks @dedekind
