### ISSUE TITLE
Errors when using ZFS On Linux Host File System

### ISSUE THREAD

**Issue by richnetdesign** [intel/bmap-tools#65]
Is there known filesystem issues with using bmap tools with files hosted on ZFS On Linux?  I had a yocto build failing at wic / bmap step due to some failed syscalls related to SEEK_HOLE.   

Is this expected? Or is this something that can be tested and worked around.  I have since changed my build folder to ext4 to workaround, but I have a large ZFS pool I would much rather be using.

I will share the full error log if interested / when I find or reproduce.

Thanks.

**Comment by dedekind** [comment]
Hi, I never used it on ZFS, so unfortunately cannot say. I remember @kad found some issues on XFS and I think hi addressed them (try digging git log). But absolutely no experience with ZFS.

**Comment by davidjenei** [comment]
We had the same issue with SEEK_HOLE and ZFS. In Filemap.py the probe_seek_hole test detected, that lseek SEEK_HOLE returned incorrect value (EOF) most of the time with our default ZFS config (zfs version 0.7.5-1ubuntu16.7). In the end setting [zfs_dmu_offset_next_sync](https://manpages.debian.org/testing/zfsutils-linux/zfs-module-parameters.5.en.html) to 1 fixed this. 
```
echo 1 >> /sys/module/zfs/parameters/zfs_dmu_offset_next_sync
```

**Comment by dedekind** [comment]
Hi, would be nice to put this info somewhere in git repo, patches are welcome, thanks!

**Comment by dellgreen** [comment]
I experienced the same problem with my yocto builds, as i have started testing Ubuntu 20.04 with experimental zfs as root/boot disk. I also use bmap-tools standalone for projects, so for me i needed a permanent fix as the sysfs fix above is temporary.

If you want a permanent fix then I added the following to /etc/modprobe.d/zfs.conf

`options zfs zfs_dmu_offset_next_sync=1`

You will also need to run the following to make sure that this change makes it into all your initramfs images

`sudo update-initramfs -u -k all`

Then reboot and you can then double check by doing the following

`cat /sys/module/zfs/parameters/zfs_dmu_offset_next_sync`

which should return "1"

**Comment by dellgreen** [comment]
I think this issue can be closed now also :)
