### ISSUE TITLE
Add ZFS runtime compatibility check

### ISSUE THREAD

**Issue by dellgreen** [intel/bmap-tools#67]
Check if files we are working on reside on a ZFS file system, if they do check that the ZFS kernel module parameters are configured to be compatible for our usage, otherwise processing will fail.

If on a ZFS file system, check /sys/module/zfs/parameters/zfs_dmu_offset_next_sync is "1" and not "0"

Related to: #65

**Comment by dellgreen** [comment]
@dedekind I'm not a python developer, but, had a quick look at Filemap.py, it looks like a good place to do the check is in the _FilemapBase class constructor, do you agree?

**Comment by dedekind** [comment]
Yes, sounds like the right place. And no worries, this was my 2nd Python program, so the code is more or less naive and straightforward.

**Comment by dellgreen** [comment]
where do i declare test dependencies in python? i assume if i import anything new into a test then the build will fail on github when the code coverage is ran?

**Comment by dellgreen** [comment]
I think this issue can be closed now :)
