### ISSUE TITLE
allow http basic auth parameters to be typed

### ISSUE THREAD

**Issue by obbardc** [intel/bmap-tools#76]
it'd be nice to ask for the password if one isn't given, so we don't have to pollute the system journal/command history with passwords

```
bmaptool copy http://user:pass@url.ext/ /dev/sda
```

**Comment by dedekind** [comment]
Hi, sure that would be nice and I would help reviewing a pull request. But I do not have bandwidth working on this myself.

**Comment by obbardc** [comment]
is a wishlist item for sure, if i get some time soon I will take a look ;-)

**Comment by dedekind** [comment]
Hello, the project was moved and now owned by a new team. Please, work with them. Check the README.md file. Thanks!
