### ISSUE TITLE
AttributeError: 'Error' object has no attribute 'with_traceback'

### ISSUE THREAD

**Issue by Daniel-Vindio** [intel/bmap-tools#78]
I am very interested in using bmaptool, but I have encountered a problem for which 
I would like some help to solve it.  

I've created a simple image and its bmap with **bmaptool 3.4**.

``$ bmaptool create - o my-image.img.gz.bmap my-image.img.gz``
``bmaptool: WARNING: all 1.3 GiB are mapped, no holes in 'my-image.img.gz''``
``bmaptool: WARNING: was the image handled incorrectly and holes were expanded?``

(By the way, I would like to know the reason or implications of this warning.)

But when I try to copy the image to its corresponding partition, it seems 
to copy, but an error occurs.

``$ bmaptool copy --bmap my-image.img.gz.bmap my-image.img.gz /dev/sda4``
``bmaptool: info: block map format version 2.0``
``bmaptool: info: 332743 blocks of size 4096 (1.3 GiB), mapped 332743 blocks``
``(1.3 GiB or 100.0%)``
``bmaptool: info: copying image 'my-image.img.gz' to block device``
``'/dev/sda4' using bmap file 'my-image.img.gz.bmap'``
``bmaptool: info: 100% copied``

``Traceback (most recent call last):``
  ``File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main``
``    "__main__", fname, loader, pkg_name)``
 `` File "/usr/lib/python2.7/runpy.py", line 72, in _run_code``
 ``  exec code in run_globals``
``  File "/bin/bmaptool/__main__.py", line 11, in <module>``
 `` File "/bin/bmaptool/bmaptools/CLI.py", line 715, in main``
 `` File "/bin/bmaptool/bmaptools/CLI.py", line 477, in copy_command``
``  File "/bin/bmaptool/bmaptools/BmapCopy.py", line 791, in copy``
``  File "/bin/bmaptool/bmaptools/BmapCopy.py", line 584, in copy``
``AttributeError: 'Error' object has no attribute 'with_traceback'``

And in fact it is not possible to mount the partition, as the file system 
is not recognized.

Thanks in advance for your help.

**Comment by dedekind** [comment]
Hi, I think this was fixed in newer versions of bmap-tools. Would you update your installation to v3.6? Thanks!

Closing for now, re-open if not satisfied with the answer, thanks!

**Comment by dedekind** [comment]
I think the fix is in this commit: 0d7f010316cf73add7a7e32d396893cd7f74239c
