### ISSUE TITLE
Podman + fuse-overlayfs errors on Fedora (Selinux)

### ISSUE THREAD

**Issue by jwinarske** [intel/bmap-tools#86]
Running container via Podman on Fedora 34 I am seeing some errors similar to zfs issue.  fuse-overlayfs is required to work around Selinux issue for Yocto build.  https://github.com/containers/podman/issues/5781

`podman --storage-opt overlay.mount_program=/usr/bin/fuse-overlayfs --storage-opt overlay.mountopt=nodev,metacopy=on,noxattrs=1 run ...`

| bmaptools.Filemap.ErrorNotSupp: FilemapFiemap: the FIEMAP ioctl is not supported by the file-system

| bmaptools.Filemap.ErrorNotSupp: the file-system does not support "SEEK_HOLE" and "SEEK_DATA" but only provides a stub implementation

**Comment by sivaece06** [comment]
Hi Joel,

I too faced the same issue and it was resolved by providing -v option. 

The option -v mounts the host directory $PWD/yocto/output in the container directory /home/dev/yocto/output. It makes all the Yocto build artefacts available on the host computer and makes them persistent between two Docker runs.

podman --storage-opt overlay.mount_program=/usr/bin/fuse-overlayfs --storage-opt overlay.mountopt=nodev,metacopy=on,noxattrs=1 run -it -v $PWD/yocto/output:/home/dev/yocto/output <DOCKER IMAGE ID>
