### ISSUE TITLE
Write to destination file/device with specified offset.

### ISSUE THREAD

**Issue by kad** [intel/bmap-tools#9]
Some people are using dd to produce multi-partitioned disk sparse images.
Usually it's done with something like this:

```
dd if=partition.img of=hdd.img bs=XXX seek=NNN count=MMM conv=notrunc,sparse
```

It would be good if "bmaptool copy" would be able to be drop-in replacement for such dd calls.
It means, user should be able to:
- specify offset (in blocks or bytes?)
- specify block size (it might be different than filesystem block size) ?
- specify blocks to write ? (to be clarified: what happen if original file or bmap contains more blocks to be written compared to what user requests ?)
- don't truncate file if we writing in the middle of it (?)

**Comment by bartosh** [comment]
This is how I changed the code of sparse_copy to satisfy wic requirements related to this issue:
diff --git a/tmp/sparse.ostro b/tmp/sparse.my
index a494407..13470ee 100644
--- a/tmp/sparse.ostro
+++ b/tmp/sparse.my
@@ -1,4 +1,4 @@
-def sparse_copy(src_fname, dst_fname, offset_mib=0):
+def sparse_copy(src_fname, dst_fname, offset=0, skip=0):
     """Efficiently copy sparse file to or into another file."""
     filemap = Filemap.filemap(src_fname)
     try:
@@ -10,8 +10,11 @@ def sparse_copy(src_fname, dst_fname, offset_mib=0):
         start = first * filemap.block_size
         end = (last + 1) * filemap.block_size

+        if start < skip < end:
+            start = skip
+
         filemap._f_image.seek(start, os.SEEK_SET)
-        dst_file.seek((offset_mib * 1024 * 1024) + start, os.SEEK_SET)
+        dst_file.seek(offset + start, os.SEEK_SET)

         chunk_size = 1024 * 1024
         to_read = end - start


I understand that it's naive not error-prone implementation. I show it here just to explain the usage of 'skip' parameter.

**Comment by kad** [comment]
Em... sorry, didn't get it. I understand change where offset would be in raw bytes, instead of megabytes like in my function... but this skip argument would simply lead to broken images, as start or end are 4k block numbers in each mapped range.

**Comment by dedekind** [comment]
Lets keep this feature request open for some time. If there are no takers, we'll close it and move to a "WishList.txt" file in the project itself.

**Comment by dedekind** [comment]
Hello, the project was moved and now owned by a new team. Please, work with them. Check the README.md file. Thanks!
