### ISSUE TITLE
noop is not a valid I/O scheduler (anymore)

### ISSUE THREAD

**Issue by svenschwermer** [intel/bmap-tools#97]
It seems like "noop" is not a valid I/O scheduler. We try to set this here: https://github.com/intel/bmap-tools/blob/72c616c8451ca0c2fc0077e1996c0e53630430f7/bmaptools/BmapCopy.py#L757

**Comment by dedekind** [comment]
Please, someone submit a fix. If someone wants to maintain this project, please speak up. It needs a lot of love.
